logging:
  level:
    org.springframework.ai.chat.client.advisor: DEBUG

spring:
  application:
    name: spring-ai-rag

  ai:
    ollama:
      base-url: http://localhost:11431
      chat:
        model: "gemma3:4b-it-q4_K_M"
#  ai:
#    mistralai:
#      chat:
#        options:
#          model: "mistral-small-latest"
#      api-key: ${MISTRAL_API_KEY}

  datasource:
    url: "jdbc:postgresql://localhost:5435/aidb"
    username: "postgres"
    password: "postgres"

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect