logging:
  level:
    org.springframework.ai.chat.client.advisor: DEBUG

spring:
  application:
    name: spring-ai-rag-ollama
  main:
    allow-circular-references: true
  datasource:
    url: jdbc:postgresql://localhost:5432/ragdb
    username: postgres
    password: postgres
  ai:
    ollama:
      chat:
        model: gemma3:4b-it-q4_K_M
      base-url: http://localhost:11431
